"""One comparison table across learners from their recorded evaluations (2026-10-08).

Reads each run's validation-set history and the safety-off results of test set v4,
the frozen suite and the reference-layout (Paper 2) set, and writes one Markdown
summary.  Nothing is re-run.

    python tools/diagnostics/learner_summary.py
    python tools/diagnostics/learner_summary.py --tags sacs0_bl3,sacs1_bl3 --out results/baseline_v3/sac_seeds.md

Test-set differences against the first tag are paired over the same episodes, with a
bootstrap 95 % interval.  Success intervals are Wilson 95 %.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
LABELS = {"sac": "SAC", "ppo": "PPO", "recurrent_ppo": "RecurrentPPO", "tqc": "TQC"}


def algo_seed(tag: str):
    head = tag.split("_bl")[0]                       # e.g. recurrent_ppos0
    algo, seed = head.rsplit("s", 1)
    return algo, int(seed)


def wilson(k: int, n: int):
    if n == 0:
        return float("nan"), float("nan")
    p, z = k / n, 1.96
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return c - h, c + h


def rate(ok: pd.Series) -> str:
    k, n = int(ok.sum()), len(ok)
    lo, hi = wilson(k, n)
    return f"{k / n:.3f} ({lo:.2f}–{hi:.2f})" if n else "—"


def frac(ok: pd.Series) -> str:
    return f"{ok.mean():.2f}" if len(ok) else "—"


def read(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        return None
    d = pd.read_csv(path, keep_default_na=False)
    if "safety" in d:
        d = d[d.safety == "off"]
    elif "supervisor" in d:
        d = d[d.supervisor == "off"]
    d = d.copy()
    d["ok"] = d.outcome == "goal"
    return d


def development(tag: str) -> dict:
    algo, seed = algo_seed(tag)
    run = ROOT / "runs" / f"{algo}_formulation_seed{seed}_{tag.split('_')[-1]}"
    hist = json.loads((run / "eval_summary.json").read_text())
    off = [h for h in hist if h.get("supervisor", "off") == "off"]
    best = max(off, key=lambda h: h["goal_rate"] - 2.0 * h["collision_rate"])   # first maximum, as selected
    return {"run": run, "best_step": best["timesteps"], "combined": best["goal_rate"],
            "collision": best["collision_rate"], "score": best["goal_rate"] - 2.0 * best["collision_rate"],
            "dev": best.get("dev/goal"), "coupled": best.get("field/goal"), "n_evals": len(off)}


def encounter(row) -> str:
    cls = str(row["class"])
    if not cls and "null" in str(row.get("cell", "")):
        cls = "null"                             # rows reused from test set v1-v3 left the null class blank
    if cls == "crossing":
        return "crossing, from port" if row.get("crossing_side") == "port" else "crossing, from starboard"
    return cls.replace("_", " ")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tags", default="sacs0_bl3,ppos0_bl3,recurrent_ppos0_bl3")
    ap.add_argument("--out", type=Path, default=ROOT / "results" / "baseline_v3" / "seed0_summary.md")
    args = ap.parse_args()
    tags = [t.strip() for t in args.tags.split(",") if t.strip()]
    names = {t: f"{LABELS[algo_seed(t)[0]]} s{algo_seed(t)[1]}" for t in tags}

    test = {t: read(ROOT / "results" / "test_set" / "v4" / t / "episodes.csv") for t in tags}
    frozen = {t: read(ROOT / "results" / "frozen_suite" / t / "episodes.csv") for t in tags}
    ref = {t: read(ROOT / "results" / "paper2_set" / t / "episodes.csv") for t in tags}
    dev = {t: development(t) for t in tags}

    L = [f"# Baseline-v3 learner comparison ({', '.join(names[t] for t in tags)})", "",
         "Generated by `tools/diagnostics/learner_summary.py` from the recorded evaluations; "
         "safety layer off throughout; each run represented by its best validation-set checkpoint. "
         "Success intervals are Wilson 95 %.", ""]

    head = "| | " + " | ".join(names[t] for t in tags) + " |"
    rule = "|---|" + "---|" * len(tags)

    L += ["## Selected checkpoint (validation set, 270 episodes)", "", head, rule]
    L.append("| Best checkpoint | " + " | ".join(f"{dev[t]['best_step'] / 1e6:.1f} M" for t in tags) + " |")
    L.append("| Combined goal / collision | " + " | ".join(f"{dev[t]['combined']:.2f} / {dev[t]['collision']:.2f}" for t in tags) + " |")
    L.append("| Selection score | " + " | ".join(f"{dev[t]['score']:+.2f}" for t in tags) + " |")
    L.append("| Decoupled (120) / coupled (150) goal | " + " | ".join(f"{dev[t]['dev']:.2f} / {dev[t]['coupled']:.2f}" for t in tags) + " |")
    L.append("")

    have = [t for t in tags if test[t] is not None]
    L += ["## Test set v4 (1,000 episodes, the headline)", "", head, rule]

    def row(label, f):
        L.append(f"| {label} | " + " | ".join(f(test[t]) if test[t] is not None else "not run" for t in tags) + " |")

    row("**Overall success**", lambda d: "**" + rate(d.ok) + "**")
    row("Decoupled (664)", lambda d: rate(d[d.source == "frozen"].ok))
    row("Coupled (336)", lambda d: rate(d[d.source == "paper2"].ok))
    row("Target collisions", lambda d: f"{(d.outcome == 'collision:target').mean():.1%}")
    row("Obstacle and boundary collisions", lambda d: f"{(d.outcome.str.startswith('collision') & (d.outcome != 'collision:target')).mean():.1%}")
    row("No-target episodes (30)", lambda d: f"{int(d[d.cell.str.contains('NT')].ok.sum())} of {int(d.cell.str.contains('NT').sum())}")
    row("Varying-speed targets (150)", lambda d: frac(d[d.variant == "VAR"].ok))
    L.append("")
    L += ["By encounter (decoupled + coupled):", "", head, rule]
    groups = ["head on", "crossing, from port", "crossing, from starboard", "overtaking", "being overtaken", "null", "no target"]
    for g in groups:
        def f(d, g=g):
            e = d.apply(encounter, axis=1)
            sub = d[e == g]
            return f"{sub.ok.mean():.2f} (n={len(sub)})" if len(sub) else "—"
        row(g.capitalize(), f)
    L.append("")

    if len(have) > 1 and have[0] == tags[0]:
        base = test[tags[0]].set_index("test_id").ok
        rng = np.random.default_rng(0)
        L += [f"Paired difference against {names[tags[0]]} (same 1,000 episodes, bootstrap 95 %):", ""]
        for t in have[1:]:
            other = test[t].set_index("test_id").ok.reindex(base.index)
            diff = (other.astype(int) - base.astype(int)).values
            boots = [rng.choice(diff, len(diff)).mean() for _ in range(4000)]
            L.append(f"- {names[t]}: {diff.mean() * 100:+.1f} points "
                     f"({np.percentile(boots, 2.5) * 100:+.1f} to {np.percentile(boots, 97.5) * 100:+.1f}); "
                     f"{int(((other == 1) & (base == 0)).sum())} episodes gained, {int(((other == 0) & (base == 1)).sum())} lost")
        L.append("")

    L += ["## Frozen suite and reference layouts", "", head, rule]
    L.append("| Frozen suite, Tier B (800, decoupled) | " + " | ".join(
        rate(frozen[t][frozen[t].set == "tier_b"].ok) if frozen[t] is not None else "not run" for t in tags) + " |")
    L.append("| Robustness set (900; reactive and non-compliant targets) | " + " | ".join(
        rate(frozen[t][frozen[t].set == "tier_b_robust"].ok) if frozen[t] is not None else "not run" for t in tags) + " |")
    L.append("| Reference layouts L1–L3 (630) | " + " | ".join(
        rate(ref[t].ok) if ref[t] is not None else "not run" for t in tags) + " |")
    L.append("| Reference layouts, no target (30) | " + " | ".join(
        f"{int(ref[t][ref[t].encounter == 'NT'].ok.sum())} of {int((ref[t].encounter == 'NT').sum())}" if ref[t] is not None else "—"
        for t in tags) + " |")
    L.append("")
    L.append("Single seeds: PPO's measured seed-to-seed spread was about 0.05 overall and 0.20 on crossings, "
             "so learner rankings need seeds 1–2.")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    print(f"-> {args.out}")


if __name__ == "__main__":
    main()
